logstash:
  image: logstash:2.4.0
  links:
    - elasticsearch:esserver
  volumes:
    - ./logstash.conf:/config/logstash.conf
    - .:/logstash-input-cloudflare
  command: logstash --pluginpath /logstash-input-cloudflare/lib/ -f /config/logstash.conf --verbose

kibana:
  image: kibana:4.6.1
  links:
    - elasticsearch:esserver
  environment:
    - ELASTICSEARCH_URL=http://esserver:9200
  ports:
    - 5601:5601

elasticsearch:
  image: elasticsearch:2.4.1
  command: bash -c "plugin install mobz/elasticsearch-head ; /docker-entrypoint.sh elasticsearch"
  ports:
    - 9200:9200
